### ISSUE TITLE
[Epic] Flashloan Providers

### ISSUE THREAD

**Issue by brozorec** [Fujicracy/fuji-v2#131]
### Balancer
- cost 0 and we have already implemented them for V1, we have to see on what chains they are available and implement them. 
- available on Arbitrum and Polygon

### Beethoven
https://beets.fi/
- approved fork of Balancer
- Optimism and Fantom

###Flashloan Providers
Balancer
- [x] Polygon #256 
- [x] Arbitrum #256 
- [x] Gnosis #256 
- [x] Optimism #256 
- [x] Mainnet #256 

Beethonven

- [ ] Optimism

**Comment by pedrovalido** [comment]
Regarding Beethoven flashloan's integration , I don't think there's any difference between them and Balancer's flashloan. I do mean ANY difference:
From the Beethoven docs, they say their deployed address on Optimism (we are not considering Fantom at the moment) for Vault is 0xBA12222222228d8Ba445958a75a0704d566BF2C8, which is the exact same as Balancer's address. Actually, this is no secret they use the exact same contracts (per the image below)


![Image](https://user-images.githubusercontent.com/80268365/213476564-54799e08-f1fe-4d13-ab91-a2a4d31f1031.png)

`Beethoven X uses Balancer V2 contracts verbatim, which have completed [several full audits](https://docs.balancer.fi/core-concepts/security/audits) and have a comprehensive [bug bounty](https://docs.balancer.fi/core-concepts/security/bug-bounties) program.`

This means, Beethoven's integration on Optimism is the same as integrating Balancer. It would be worth checking Beethoven's flashloans in Fantom is we get to that point.

**Comment by DaigaroCota** [comment]
@pedrovalido to review liquidity on Gnosis, and why forking test pass.

**Comment by pedrovalido** [comment]
After a bit of research I realized I made a mistake of using borrow amount 100e6 in the forking test for wxdai. That's why the tests were passing. WXDAI is 18 decimals and after changing the borrow amount to 100e18 the tests fail with error code BAL528 (from their documentation INSUFFICIENT_FLASH_LOAN_BALANCE). This confirms that Balancer has very low liquidity on Gnosis (79 WXDAI to be more precise at the moment).
I've asked on telegram if they have any idea if this might change in the future.
