### ISSUE TITLE
[CrossFuji] Deploy Scripts in Hardhat using plugin hardhat-deploy

### ISSUE THREAD

**Issue by iafhurtado** [Fujicracy/fuji-v2#30]

**Comment by brozorec** [comment]
- FE needs addresses on Goerli and Mumbai

**Comment by DaigaroCota** [comment]
@brozorec  Is deploying vaults part of the deploy routine? Or we will only handle that on-chain? 

The answer from what I am seeing is no, but I think there will be front-end implications here. that perhaps we handle on the SDK side. Otherwise, there is more work to do here since the `hardhat-deploy`  plug-in does not handle storage of the on-chain operations that will generate the vaults.

**Comment by brozorec** [comment]
We may try to store in the factories:

- mapping debtToken -> Vaults
- mapping collateralToken -> Vaults
- array of all debtTokens
- arrays of all collateralTokens

Like this, we keep the deployment of a new vault as an on-chain routine.

**Comment by DaigaroCota** [comment]
Additional observation. As currently defined, in BorrowingVaultFactory.sol, contract address creation will collide for vaults with the same assets but different providers. The salt created is the hash of just: asset, debtAsset, oracle, and chief. For two vaults with the same parameters before but with different providers (in example Class A providers, vs Class B providers), this will result in revert txs.
