### ISSUE TITLE
Research Bulker in Compound

### ISSUE THREAD

**Issue by pedrovalido** [Fujicracy/fuji-v2#689]

**Comment by DaigaroCota** [comment]
I provided feedback on why the Compound Bulker.sol contract is safe to use without additional signatures or checks.
The Bulker.sol checks that the caller is the `msg.sender` of the set of actions that will be performed.
That way there is no risk of a third party taking advantage of the "operator" role that the Bulker has. 

In our particular case, we have to implement a form of signature because our HimalyaCompound.sol is not called by the owner of the actions to be performed. 

That is why we need carry some type of permit, as we do similarly in our BaseRouter.sol process.
@pedrovalido 

Just note this and close issue.
